name: ci

on: [push, pull_request]

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2 # So golangci-lint can do git diff HEAD~1

      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: false
          
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      
      - name: Build
        run: make build

      - name: Smoke Test
        run: ./eksdemo version